spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: processr
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      org.hibernate.envers.audit_table_prefix: zaud_
  datasource:
    
    url: jdbc:postgresql://localhost:5432/processes
    
    username: postgres
    password: Ericmullo4
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  jackson:
    time-zone: 'America/Guayaquil'
  sql:
    init:
      platform: postgres
server:
  port: 4445 #local
  #port: 4444 #pruebas
logging:
  level:
    org.springframework.web: error
    org.springframework.jpa: error
    org.hibernate: error




